version: '3.8'

services:
  mariadb:
    image: mariadb:10.9
    container_name: parcial_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: parcial
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - parcial_net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p12345"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    image: juancavelez/parcial-docker-app
    container_name: parcial_app
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - parcial_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://parcial:mariadb:3306/parcial
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345

volumes:
  mariadb_data:

networks:
  parcial_net:
